python train.py ./config/MNIST.yaml
python train.py ./config/MNIST1.yaml
python train.py ./config/MNIST2.yaml
python train.py ./config/MNIST3.yaml
python train.py ./config/MNIST4.yaml
python train.py ./config/MNIST5.yaml
python train.py ./config/MNIST6.yaml
python train.py ./config/MNIST7.yaml
python train.py ./config/MNIST8.yaml
python train.py ./config/MNIST9.yaml