python train.py ./config/cifar10/plane.yaml
python train.py ./config/cifar10/car.yaml
python train.py ./config/cifar10/bird.yaml
python train.py ./config/cifar10/cat.yaml
python train.py ./config/cifar10/deer.yaml
python train.py ./config/cifar10/dog.yaml
python train.py ./config/cifar10/frog.yaml
python train.py ./config/cifar10/horse.yaml
python train.py ./config/cifar10/ship.yaml
python train.py ./config/cifar10/truck.yaml
